### ISSUE TITLE
Error: Uncaught TypeError: map.setView is not a function

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/sitenow_maps#28] opened 2017-06-16 03:58 UTC
When rendering a map an error occurs:  
```js
map.setView([arcdata[0].attributes.Lati,arcdata[0].attributes.Longi], 17);
```

**Comment by markahrens** [comment] 2017-06-16 13:14
Closing, duplicate of #19

**Closed by markahrens** 2017-06-16 13:14 UTC
